# Generated by Django 3.0 on 2020-08-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200822_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
